# Generated by Django 5.0.6 on 2024-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='vendor',
            field=models.ManyToManyField(to='vendors.vendors'),
        ),
    ]
