# Generated by Django 5.0.6 on 2024-05-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
