# Generated by Django 5.0.6 on 2024-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_rename_vendor_market_vendors'),
        ('vendors', '0002_rename_vendors_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='vendors',
            field=models.ManyToManyField(related_name='market', to='vendors.vendor'),
        ),
    ]
