# Generated by Django 5.0.6 on 2024-05-23 07:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_rename_vendor_market_vendors'),
        ('products', '0003_rename_products_product'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
